name: flutter_mkd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^5.1.6
  riverpod: ^2.1.1
  supabase: ^1.3.1
  gotrue: ^1.12.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
