name: flutter_mkd
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
