name: flutter_mkd
description: A business management application for the Indian market

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-7.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Navigation
  go_router: ^5.1.6

  # State Management
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6
  provider: ^6.0.5

  # Supabase
  supabase_flutter: ^1.10.3
  gotrue: ^1.10.3
  
  # Utilities
  intl: ^0.19.0
  logging: ^1.2.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.1.1
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic