dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  supabase_flutter: ^1.10.25
  flutter_riverpod: ^2.4.9
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
